name: Update PNG from Drawio

on:
  push:
    branches: [main]
    paths:
      - '**.drawio'

jobs:
  update-png:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      drawio:
        image: jgraph/drawio
        ports:
          - 8080:8080
        volumes:
          - ./:/data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait for drawio service
        run: |
          while ! curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for drawio service..."
            sleep 5
          done
          echo "Drawio service is up!"

      - name: Convert drawio to PNG
        run: |
          for DRAWIO_FILE in ${{ steps.changed-files.outputs.modified_files }}; do
            PNG_FILE="${DRAWIO_FILE%.drawio}.png"
            echo "Processing $DRAWIO_FILE to $PNG_FILE"

            # Исправленный curl с параметрами scale и page
            curl -X POST "http://localhost:8080/convert" \
              -F "file=@$DRAWIO_FILE" \
              -F "format=png" \
              -F "scale=2" \  # [[5]] Увеличение масштаба для четкости
              -F "page=1" \   # Указываем страницу (если диаграмма многостраничная)
              -o "$PNG_FILE" \
              --fail          # [[10]] Ошибка при HTTP-ошибке

            # Проверка HTTP-кода
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/convert")
            if [ "$HTTP_CODE" -ne 200 ]; then
              echo "HTTP Error: $HTTP_CODE"
              exit 1
            fi

            # Проверка размера файла
            if [ ! -s "$PNG_FILE" ]; then
              echo "Ошибка конвертации: $DRAWIO_FILE"
              exit 1
            fi

            # Обновление README.md
            PNG_NAME=$(basename "$PNG_FILE")
            sed -i "s|!\[.*\]\(.*\.\(svg\|png\)\)|![$PNG_NAME]($PNG_NAME)|g" README.md
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.png README.md || echo "Nothing to add"
          git commit -m "Auto-update PNGs for modified .drawio files" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}