name: Update SVG from Drawio

on:
  push:
    branches: [main]
    paths:
      - '**.drawio'

jobs:
  update-svg:
    runs-on: ubuntu-latest
    services:
      drawio:
        image: jgraph/drawio 
        ports:
          - 8080:8080
        volumes:
          - ./:/data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait for drawio service
        run: |
          while ! curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for drawio service..."
            sleep 2
          done
          echo "Drawio service is up!"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.drawio'

      - name: Convert drawio to SVG
        run: |
          for DRAWIO_FILE in ${{ steps.changed-files.outputs.modified_files }}; do
            SVG_FILE="${DRAWIO_FILE%.drawio}.svg"
            echo "Processing $DRAWIO_FILE to $SVG_FILE"

            # Используем API draw.io через curl
            curl -X POST "http://localhost:8080/convert" \
              -F "file=@$DRAWIO_FILE" \
              -F "format=svg" \
              -o "$SVG_FILE"

            if [ $? -ne 0 ]; then
              echo "Failed to convert $DRAWIO_FILE"
              exit 1
            fi

            ls -la "$SVG_FILE"

            # Обновляем README.md
            SVG_NAME=$(basename "$SVG_FILE")
            echo "Updating README.md with: $SVG_NAME"
            if grep -q "\.svg" README.md; then
              sed -i "s|\!\[.*\](.*\.svg)|\!\[${SVG_NAME%.*}\](${SVG_NAME})|g" README.md
            else
              echo "No SVG reference found in README.md"
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.svg README.md || echo "Nothing to add"
          git commit -m "Auto-update SVGs for modified .drawio files" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}