name: Update PNG from Drawio

on:
  push:
    branches: [main]
    paths:
      - '**.drawio'

jobs:
  update-png:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # [[1]] Для полной истории коммитов

      - name: Get changed files
        id: changed_files
        run: |
          # Проверяем, есть ли предыдущий коммит
          if git rev-parse --verify HEAD~1 > /dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          else
            # Если первый коммит, берем все файлы
            CHANGED_FILES=$(git ls-files)
          fi
          echo "::set-output name=files::${CHANGED_FILES}"

      - name: Filter .drawio files
        id: drawio_files
        run: |
          DRAWIO_FILES=$(echo "${{ steps.changed_files.outputs.files }}" | grep -E '\.drawio$')
          echo "::set-output name=files::${DRAWIO_FILES}"

      - name: Convert drawio to PNG
        if: steps.drawio_files.outputs.files != ''
        run: |
          for DRAWIO_FILE in ${DRAWIO_FILES}; do
            PNG_FILE="${DRAWIO_FILE%.drawio}.png"
            echo "Processing $DRAWIO_FILE to $PNG_FILE"

            curl -X POST "http://localhost:8080/convert" \
              -F "file=@$DRAWIO_FILE" \
              -F "format=png" \
              -F "scale=2" \
              -F "page=1" \
              -o "$PNG_FILE" \
              --fail

            # Проверки HTTP и размера файла
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/convert")
            if [ "$HTTP_CODE" -ne 200 ]; then
              echo "HTTP Error: $HTTP_CODE"
              exit 1
            fi

            if [ ! -s "$PNG_FILE" ]; then
              echo "Ошибка конвертации: $DRAWIO_FILE"
              exit 1
            fi

            # Обновление README.md
            PNG_NAME=$(basename "$PNG_FILE")
            sed -i "s|!\[.*\]\(.*\.\(svg\|png\)\)|![$PNG_NAME]($PNG_NAME)|g" README.md
          done
        env:
          DRAWIO_FILES: ${{ steps.drawio_files.outputs.files }}

      - name: Commit and push changes
        if: steps.drawio_files.outputs.files != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.png README.md || echo "Nothing to add"
          git commit -m "Auto-update PNGs for modified .drawio files" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}