name: Update SVG from Drawio
on:
  push:
    branches: [main]
    paths:
      - '**.drawio'
jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install drawio-export-cli
        run: |
          npm install -g drawio-export-cli
          drawio-export --version  # Проверка установки

      - name: Get modified drawio file
        id: drawio
        run: |
          # Ищем измененные/новые .drawio файлы
          DRAWIO_FILE=$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep '\.drawio$' | head -1)
          echo "drawio_file=${DRAWIO_FILE:-none}" >> $GITHUB_OUTPUT
          echo "svg_file=${DRAWIO_FILE%.drawio}.svg" >> $GITHUB_OUTPUT
        shell: bash

      - name: Debug output
        run: |
          echo "Modified drawio file: ${{ steps.drawio.outputs.drawio_file }}"
          echo "Target SVG file: ${{ steps.drawio.outputs.svg_file }}"
          ls -la  # Проверяем содержимое директории

      - name: Generate SVG
        if: steps.drawio.outputs.drawio_file != 'none'
        run: |
          drawio-export --format svg ${{ steps.drawio.outputs.drawio_file }}
          ls -la ${{ steps.drawio.outputs.svg_file }}  # Проверяем созданный SVG

      - name: Update README.md
        if: steps.drawio.outputs.drawio_file != 'none'
        run: |
          SVG_NAME=$(basename ${{ steps.drawio.outputs.svg_file }})
          echo "Updating README.md with: $SVG_NAME"
          # Безопасная замена с проверкой существования
          if grep -q "\.svg" README.md; then
            sed -i "s|\!\[.*\](.*\.svg)|\!\[${SVG_NAME%.*}\](${SVG_NAME})|g" README.md
          else
            echo "No SVG reference found in README.md"
          fi

      - name: Commit and push changes
        if: steps.drawio.outputs.drawio_file != 'none'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ steps.drawio.outputs.svg_file }} README.md || echo "Nothing to add"
          git commit -m "Auto-update SVG for ${{ steps.drawio.outputs.drawio_file }}" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}