name: Update SVG from Drawio

on:
  push:
    branches: [main]
    paths:
      - '**.drawio'

jobs:
  update-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      drawio:
        image: jgraph/drawio
        ports:
          - 8080:8080
        volumes:
          - ./:/data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait for drawio service
        run: |
          while ! curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for drawio service..."
            sleep 2
          done
          echo "Drawio service is up!"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.drawio'

      - name: Convert drawio to SVG
        run: |
          for DRAWIO_FILE in ${{ steps.changed-files.outputs.modified_files }}; do
            SVG_FILE="${DRAWIO_FILE%.drawio}.svg"
            echo "Processing $DRAWIO_FILE to $SVG_FILE"

            curl -X POST "http://localhost:8080/convert" \
              -F "file=@$DRAWIO_FILE" \
              -F "format=svg" \
              -o "$SVG_FILE"

            if [ $? -ne 0 ]; then
              echo "Failed to convert $DRAWIO_FILE"
              exit 1
            fi

            # Обновление README.md
            SVG_NAME=$(basename "$SVG_FILE")
            sed -i "s|!\[.*\]\(.*\.svg\)|![$SVG_NAME]|g" README.md
          done

      - name: Commit and push changes
        run: |
          # Используем стандартные настройки для GitHub Actions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # Без префикса [[6]]
          git add *.svg README.md || echo "Nothing to add"
          git commit -m "Auto-update SVGs for modified .drawio files" || exit 0
          # Используем GITHUB_TOKEN для аутентификации
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}