name: Update PNG from Drawio

on:
  push:
    branches: [main]
    paths:
      - '**.drawio'

jobs:
  update-png:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        run: |
          if git rev-parse --verify HEAD~1 > /dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only --diff-filter=d HEAD~1 HEAD)
          else
            CHANGED_FILES=$(git ls-files)
          fi
          echo "changed_files=${CHANGED_FILES}" >> $GITHUB_OUTPUT
            
      - name: Filter .drawio files
        id: drawio_files
        run: |
          DRAWIO_FILES=$(echo "${{ steps.changed_files.outputs.changed_files }}" | grep -E '\.drawio$' | xargs -I {} sh -c '[ -f "{}" ] && echo {}')
          echo "drawio_files=${DRAWIO_FILES}" >> $GITHUB_OUTPUT

      - name: Convert drawio to PNG
        if: steps.drawio_files.outputs.drawio_files != ''
        run: |
          mkdir -p diagrams
          for DRAWIO_FILE in ${DRAWIO_FILES}; do
            echo "Processing $DRAWIO_FILE"
            if [ ! -f "$DRAWIO_FILE" ]; then
              echo "File not found: $DRAWIO_FILE"
              continue
            fi
            
            # Исправленный запуск Docker без --user [[6]]
            docker run --rm \
              -v ${PWD}:/workspace \
              -v ${PWD}/diagrams:/output \
              rlespinasse/drawio-export \
              -f png --no-page-suffix -t -o /output /workspace/"$DRAWIO_FILE"
            
            BASENAME=$(basename "${DRAWIO_FILE%.drawio}")
            PNG_FILE="${BASENAME}.png"
            
            if [ ! -f "diagrams/$PNG_FILE" ]; then
              echo "Error: diagrams/$PNG_FILE not generated" >&2
              exit 1
            fi

            sed -i "s|!\[.*\](.*\.\(svg\|png\))|![$PNG_FILE](diagrams/$PNG_FILE)|g" README.md
          done
        env:
          DRAWIO_FILES: ${{ steps.drawio_files.outputs.drawio_files }}

      - name: Commit and push changes
        if: steps.drawio_files.outputs.drawio_files != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add diagrams/*.png README.md || echo "Nothing to add"  # Исправлен путь [[1]]
          git commit -m "Auto-update PNGs for modified .drawio files" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}