name: Update SVG from Drawio
on:
  push:
    branches: [main]
    paths:
      - '**.drawio'

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Drawio headless
        run: |
          sudo apt update
          sudo apt install -y xvfb
          sudo snap install drawio

      - name: Get and process modified drawio files
        id: process_drawio
        run: |
          # Get the list of modified .drawio files
          MODIFIED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.drawio$')
          for DRAWIO_FILE in $MODIFIED_FILES; do
            if [[ -n "$DRAWIO_FILE" ]]; then
              SVG_FILE="${DRAWIO_FILE%.drawio}.svg"
              echo "Processing $DRAWIO_FILE to $SVG_FILE"
              xvfb-run --auto-servernum drawio-desktop --headless --export --format svg --output "$SVG_FILE" "$DRAWIO_FILE"
              ls -la "$SVG_FILE"

              # Update README.md with the new SVG file
              SVG_NAME=$(basename "$SVG_FILE")
              echo "Updating README.md with: $SVG_NAME"
              if grep -q "\.svg" README.md; then
                sed -i "s|\!\[.*\](.*\.svg)|\!\[${SVG_NAME%.*}\](${SVG_NAME})|g" README.md
              else
                echo "No SVG reference found in README.md"
              fi
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.svg README.md || echo "Nothing to add"
          git commit -m "Auto-update SVGs for modified .drawio files" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
