name: Update SVG from Drawio

on:
  push:
    branches: [main]
    paths:
      - '**.drawio'

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.drawio'

      - name: Convert drawio to SVG
        run: |
          for DRAWIO_FILE in ${{ steps.changed-files.outputs.modified_files }}; do
            SVG_FILE="${DRAWIO_FILE%.drawio}.svg"
            echo "Processing $DRAWIO_FILE to $SVG_FILE"

            # Use drawio to convert the file
            docker run --rm -v "$(pwd):/data" jgraph/drawio:stable \
              /usr/share/drawio/drawio.sh --export "/data/$DRAWIO_FILE" --format svg --output "/data/$SVG_FILE"

            if [ $? -ne 0 ]; then
              echo "Failed to convert $DRAWIO_FILE"
              exit 1
            fi

            ls -la "$SVG_FILE"

            # Update README.md with the new SVG file
            SVG_NAME=$(basename "$SVG_FILE")
            echo "Updating README.md with: $SVG_NAME"
            if grep -q "\.svg" README.md; then
              sed -i "s|\!\[.*\](.*\.svg)|\!\[${SVG_NAME%.*}\](${SVG_NAME})|g" README.md
            else
              echo "No SVG reference found in README.md"
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.svg README.md || echo "Nothing to add"
          git commit -m "Auto-update SVGs for modified .drawio files" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}