name: Update SVG from Drawio
on:
  push:
    branches: [main]
    paths:
      - '**.drawio'

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xvfb libgl1-mesa-glx libgl1-mesa-dri libxcb-xinerama0 libxcb-util1 libxcb-xrm0 libxcb-xkb1 libxcb-shape0 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shm0 libxcb-xrm0 libxcb-xv0 libxcb-xkb1 libxcb-cursor0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb-util1
          sudo snap install drawio

      - name: Start xvfb
        run: Xvfb :99 -screen 0 1024x768x24 &

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.drawio'

      - name: Process modified drawio files
        run: |
          for DRAWIO_FILE in ${{ steps.changed-files.outputs.modified_files }}; do
            SVG_FILE="${DRAWIO_FILE%.drawio}.svg"
            echo "Processing $DRAWIO_FILE to $SVG_FILE"
            xvfb-run --auto-servernum --server-num=99 drawio --headless --export --format svg --output "$SVG_FILE" "$DRAWIO_FILE"
            ls -la "$SVG_FILE"

            # Update README.md with the new SVG file
            SVG_NAME=$(basename "$SVG_FILE")
            echo "Updating README.md with: $SVG_NAME"
            if grep -q "\.svg" README.md; then
              sed -i "s|\!\[.*\](.*\.svg)|\!\[${SVG_NAME%.*}\](${SVG_NAME})|g" README.md
            else
              echo "No SVG reference found in README.md"
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.svg README.md || echo "Nothing to add"
          git commit -m "Auto-update SVGs for modified .drawio files" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
